### ISSUE TITLE
Separating Chorus from main vocal

### ISSUE THREAD

**Issue by SutirthaChakraborty** [zafarrafii/REPET-Python#2]
How can we do that?

**Comment by zafarrafii** [comment]
Hi Sutirtha. If by chorus, you mean the part of the song that is repeated between verses (i.e., the refrain), you should be able to remove the main vocals from it using any of the REPET methods (see the provided examples). If perhaps you meant the backing vocals that can happen in the background of the main vocals, unless they somehow repeat with the accompaniment, an approach like REPET will not work; if the backing vocals are quite dense, a method like REPET-SIM could remove some of them. Note that REPET is a simple and blind approach which is solely based on identifying repetitions, more recent audio separation approaches are based on deep learning models and are able to separate pretty much anything with pretty good results (as long as they were trained on the relevant data), so I would suggest you have a look online for those, or you could also build/train your own special model if needed. Best.

**Comment by SutirthaChakraborty** [comment]
Sorry for the confusion. I was talking about about backing vocals. Do you know if a pre-trained weight can do so?  
Super thanks for you reply. We can close the issue if you want.

**Comment by zafarrafii** [comment]
I am not really aware of models which specifically isolate the main vocals from backing vocals, but you can find a bunch of pre-trained music source separation models which could probably work ([Open-Unmix](https://github.com/sigsep/open-unmix-pytorch), [Spleeter](https://github.com/deezer/spleeter), [Asteroid](https://github.com/asteroid-team/asteroid), and more online). Of course!
